### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by masterkain** [stefanprodan/k8s-podinfo#21]
I'm following https://medium.com/@stefanprodan/running-kubernetes-on-scaleway-bare-metal-with-terraform-and-kubeadm-1cf18aae32d5
and I'm in the process of updating everything to the most recent versions of the involved software (terraform, metrics-server versions, kubernetes versions, etc.)

I'm almost done, but I'm trying out the podinfo deploy but I have just an error message in pod logs when starting the container this way:

```
$ kubectl --kubeconfig ./$(terraform output kubectl_config) \
>   apply -f https://raw.githubusercontent.com/stefanprodan/k8s-podinfo/master/deploy/auto-scaling/podinfo-svc-nodeport.yaml
service/podinfo-nodeport created

kubectl --kubeconfig ./$(terraform output kubectl_config) \
>   apply -f https://raw.githubusercontent.com/stefanprodan/k8s-podinfo/master/deploy/auto-scaling/podinfo-dep.yaml
deployment.apps/podinfo created
```

```
standard_init_linux.go:211: exec user process caused "exec format error"
```
![Screen Shot 2019-08-04 at 01 00 27](https://user-images.githubusercontent.com/12844/62417580-48b6ef80-b653-11e9-82fa-a1091554ae52.png)
![Screen Shot 2019-08-04 at 01 01 01](https://user-images.githubusercontent.com/12844/62417584-65ebbe00-b653-11e9-81a4-937ab59237f0.png)

**Comment by masterkain** [comment]
arch issues

**Comment by ddimasik** [comment]
Try to use image for another arch like amd64 or darwin
