### ISSUE TITLE
Whether to consider adding log collection？

### ISSUE THREAD

**Issue by yangwenmai** [stefanprodan/k8s-podinfo#4]
use elk on k8s.

**Comment by stefanprodan** [comment]
ELK is not an option for Kubernetes, the official way of doing log collection is with Fluentd and based on your cloud vendor you would use Cloudwatch or Stakdriver. For on-prem/bare-metal setup you would use ElasticSearch.

From an application perspective as log as you log in JSON format like `podinfo` does, Fluentd will push those logs into whatever backend you use.
